/*
 * The contents of this file are subject to the Common Public Attribution License Version 1.0.
 * (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 * https://github.com/Slion/Fulguris/blob/main/LICENSE.CPAL-1.0.
 * The License is based on the Mozilla Public License Version 1.1, but Sections 14 and 15 have been
 * added to cover use of software over a computer network and provide for limited attribution for
 * the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS" basis, WITHOUT WARRANTY OF
 * ANY KIND, either express or implied. See the License for the specific language governing rights
 * and limitations under the License.
 *
 * The Original Code is Fulguris.
 *
 * The Original Developer is the Initial Developer.
 * The Initial Developer of the Original Code is Stéphane Lenclud.
 *
 * All portions of the code written by Stéphane Lenclud are Copyright © 2020 Stéphane Lenclud.
 * All Rights Reserved.
 */

package fulguris.cursor

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.PorterDuff
import android.graphics.drawable.Drawable
import android.util.AttributeSet
import android.view.View
import androidx.appcompat.content.res.AppCompatResources
import fulguris.R

/**
 * Transparent overlay that renders the mouse cursor for [CursorController].
 *
 * The cursor graphic is the `arrow_selector_tool` Material Symbol (see
 * [R.drawable.ic_arrow_selector_tool_fill], generated by `scripts/tools/add_md_icon.py`). To stay
 * legible on top of arbitrary web content it is drawn as a dark outline behind a white fill.
 *
 * This view owns nothing but its rendering: position is pushed in via [setPosition] and the visible
 * bounds it clamps to are simply its own measured size, exposed through [maxX]/[maxY]. Keeping it
 * free of any browser specifics is what lets the whole `cursor` package be reused elsewhere.
 */
class CursorView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : View(context, attrs, defStyleAttr) {

    // Cursor size in pixels.
    private val cursorSize = (36f * resources.displayMetrics.density)

    // The pointer tip within the icon. The arrow_selector_tool vector has its tip near the
    // (240, 80) point of its 960x960 viewport, hence these ratios. The tip is the hotspot: it is
    // what sits exactly at the logical cursor coordinates.
    private val hotspotX = cursorSize * (240f / 960f)
    private val hotspotY = cursorSize * (80f / 960f)

    // White fill drawn on top.
    private val fill: Drawable = AppCompatResources.getDrawable(context, R.drawable.ic_arrow_selector_tool_fill)!!
        .mutate().apply {
            setColorFilter(Color.WHITE, PorterDuff.Mode.SRC_IN)
            setBounds(0, 0, cursorSize.toInt(), cursorSize.toInt())
        }

    // Slightly larger dark copy drawn behind the fill so the cursor reads against light pages.
    private val outlineWidth = (2.5f * resources.displayMetrics.density)
    private val outline: Drawable = AppCompatResources.getDrawable(context, R.drawable.ic_arrow_selector_tool_fill)!!
        .mutate().apply {
            setColorFilter(Color.argb(200, 0, 0, 0), PorterDuff.Mode.SRC_IN)
        }

    private var cursorX = 0f
    private var cursorY = 0f

    /** Largest valid cursor coordinates (keeps the tip inside the overlay). */
    val maxX: Float get() = width.toFloat()
    val maxY: Float get() = height.toFloat()

    init {
        // Purely decorative: never intercept focus or touch.
        isFocusable = false
        isClickable = false
    }

    fun setPosition(x: Float, y: Float) {
        cursorX = x
        cursorY = y
        invalidate()
    }

    override fun onDraw(canvas: Canvas) {
        super.onDraw(canvas)
        val left = cursorX - hotspotX
        val top = cursorY - hotspotY

        // Outline: same shape, expanded by outlineWidth on every side.
        val o = outlineWidth
        outline.setBounds(0, 0, (cursorSize + 2 * o).toInt(), (cursorSize + 2 * o).toInt())
        canvas.save()
        canvas.translate(left - o, top - o)
        outline.draw(canvas)
        canvas.restore()

        canvas.save()
        canvas.translate(left, top)
        fill.draw(canvas)
        canvas.restore()
    }
}
